name: Price Tracker

# Controls when the workflow will run
on:
  schedule:
    # Run every day at midnight (UTC)
    - cron: '0 0 * * *'
  push:
    branches:
      - main  # This runs on every push to the 'main' branch

jobs:
  price-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust if you're using a specific version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the price-tracking script
      - name: Run price tracker
        run: |
          python main.py  # Adjust the script name if necessary
